version: "3"
services:
  web:
    image: "${CONTAINER_IMAGE}"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      # resources:
      #   limits:
      #     cpus: "0.1"
      #     memory: 50M
    environment:
      TOKEN: ${TOKEN}
      SERVICE_NAME: "{{.Service.Name}}"
      TASK_SLOT: "{{.Task.Slot}}"
