version: "3"
services:
  web:
    image: "${CONTAINER_IMAGE}"
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.type==public]
      restart_policy:
        condition: on-failure
      # resources:
      #   limits:
      #     cpus: "0.1"
      #     memory: 50M
    environment:
      FSQR_CLIENT_ID: ${FSQR_CLIENT_ID}
      FSQR_CLIENT_SECRET: ${FSQR_CLIENT_SECRET}
      TOKEN: ${TOKEN}
      SERVICE_NAME: "{{.Service.Name}}"
      TASK_SLOT: "{{.Task.Slot}}"
