version: "3"
services:
  web:
    image: "${CONTAINER_IMAGE}"
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.type==public]
      restart_policy:
        condition: on-failure
      # resources:
      #   limits:
      #     cpus: "0.1"
      #     memory: 50M
    environment:
      config__token: ${config__token}
      config__foursquare__clientId: ${config__foursquare__clientId}
      config__foursquare__clientSecret: ${config__foursquare__clientSecret}
      SERVICE_NAME: "{{.Service.Name}}"
      TASK_SLOT: "{{.Task.Slot}}"
