version: "3"
services:
  web:
    image: "${CONTAINER_IMAGE}"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "${EXPOSE_PORTTT}:8080"
