name: trigger gitlab job
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger Job
      uses: appleboy/gitlab-ci-action@master
      with:
        url: "https://git.isuvorov.com"
        token: ${{ secrets.GITLAB_TOKEN }}
        project_id: 19